let mongoose = require('mongoose')

let productDataSchema = new mongoose.Schema({
    partName:String,
    partRevision: String,
    jobNumber: String,
    firstApproval: String,
    vis_attr_description1: String,
    vis_attr_description2: String,
    vis_attr_description3: String,
    vis_attr_description4: String,
    vis_attr_description5: String,
    vis_attr_description6: String,
    vis_attr_description7: String,
    vis_attr_description8: String,
    vis_attr_description9: String,
    vis_attr_description10: String,
    mes_attr_description1: String,
    mes_attr_description2: String,
    mes_attr_description3: String,
    mes_attr_description4: String,
    mes_attr_description5: String,
    mes_attr_description6: String,
    mes_attr_description7: String,
    mes_attr_description8: String,
    mes_attr_description9: String,
    mes_attr_description10: String,
    mes_min1: String,
    mes_min2: String,
    mes_min3: String,
    mes_min4: String,
    mes_min5: String,
    mes_min6: String,
    mes_min7: String,
    mes_min8: String,
    mes_min9: String,
    mes_min10: String,
})

module.exports = mongoose.model('productData', productDataSchema)